### PR TITLE
use hoe for crops

### PR DESCRIPTION
**Pull request by noramibu**

### CODE REVIEW

**Comment by noramibu** [comment]
@mfnalex eh

**Comment by mfnalex** [comment]
Have you tested whether this also works nicely when a player doesn't have a hoe?

**Comment by Cazcez** [comment]
> Have you tested whether this also works nicely when a player doesn't have a hoe?

it works perfectly fine
https://youtu.be/tpl-a6rmAYI

**Comment by noramibu** [comment]
yeah, it works pretty fine

**Comment by noramibu** [comment]
@mfnalex uh

**Pull request merged**
